### PR TITLE
Added support for password hashes

### PR DESCRIPTION
**Pull request by nnam**
Allow the use hashes in the format of LM_HASH:NT_HASH in place of a password.

### CODE REVIEW

**Comment by jborean93** [comment]
Hey @nnam thanks for the PR, I can see this only really works with NTLMv1 hashes so I don't really have too much of an issue merging this in. The only thing I would ask for is to create some test cases to cover what you have changed.

Just out of curiosity are you still using NTLMv1 for any of your stuff, it is horribly outdated and should be avoided where possible.

**Comment by nnam** [comment]
No problem. Definitely agree! NTLMv1 is mostly for backwards compatibility with some legacy systems.

**Comment by jborean93** [comment]
Thanks @nnam I'll look at doing a release sometime soon to incorporate your changes.

**Comment by jborean93** [comment]
Hey @nnam I've created a release under `1.0.5` with your changes in it, https://pypi.python.org/pypi/ntlm-auth.

**Comment by nnam** [comment]
Excellent! Thanks for the update.

**Pull request merged**
