### PR TITLE
Added extra copyright info and include license file in package

### PR DESCRIPTION
**Pull request by jborean93**
Fixes https://github.com/jborean93/ntlm-auth/issues/16

Also bumps version to 1.0.6 for next release.

### CODE REVIEW

**Comment by jakirkham** [comment]
Might want to include 2017 in your copyright, but I leave that up to you. Otherwise LGTM.

**Comment by jborean93** [comment]
I wrote the stuff last year so will leave it as 2016, thanks for looking over it.

**Comment by jakirkham** [comment]
Thanks! :)

**Comment by jakirkham** [comment]
Should have asked, is there a PyPI release planned as well?

**Comment by jborean93** [comment]
Just did it a few minutes ago https://pypi.python.org/pypi/ntlm-auth/1.0.6

**Comment by jakirkham** [comment]
Great, thanks! :)

**Comment by jakirkham** [comment]
^

cc @synapticarbors

**Pull request merged**
